openapi: 3.0.3
info:
  title: TEMZ API
  description: |-
    This is a TEMZ Server based on the OpenAPI 3.0 specification.

    Some useful links:
    - [TEMZ server repository](https://github.com/yeongbba/temz-server)
    - [The source API definition for TEMZ](https://github.com/yeongbba/temz-server/blob/dev/src/api/openapi.yaml)
  termsOfService: https://temz.io/terms
  contact:
    email: info@temz.com
  version: 1.0.0
externalDocs:
  description: Go to TEMZ website
  url: https://temz.io
servers:
  - url: 'http://localhost:8080'
tags:
  - name: auth
    description: Methods to handle authentication
  - name: verify
    description: Methods to verify mobile phone
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            failures:
              - code: minLength.openapi.validation
                message: must NOT have fewer than 3 characters
                status: 400
                reason: name
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            invalid-value:
              value:
                failures:
                  - code: invalid-value
                    message: Authentication token is invalid
                    status: 401
            null-arguments:
              value:
                failures:
                  - code: null-arguments
                    message: Authentication token should not be null
                    status: 401
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            failures:
              - code: not-found
                message: The specified resource was not found
                status: 404
    TooManyRequest:
      description: Too Many Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            failures:
              - code: too-many-request
                message: Sent too many requests
                status: 429
    InternalServer:
      description: Internal server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            failures:
              - code: internal-server
                message: Internal Server Error
                status: 500
  schemas:
    Error:
      type: object
      properties:
        failures:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
              status:
                type: integer
                format: int32
              reason:
                type: string
            required:
              - code
              - message
              - status
      required:
        - failures
      example:
        failures:
          - code: invalid-value
            message: Invalid user or password
            status: 401
          - code: minLength.openapi.validation
            message: must NOT have fewer than 3 characters
            status: 400
            reason: name
  securitySchemes:
    jwtAuth:
      description: Bearer token authorization with JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
    csrf:
      type: apiKey
      in: header
      name: temz-csrf-token
security:
  - jwtAuth: []
    csrf: []
