openapi: 3.0.3
info:
  title: TEMZ API
  description: |-
    This is a TEMZ Server based on the OpenAPI 3.0 specification.

    Some useful links:
    - [TEMZ server repository](https://github.com/yeongbba/temz-server)
    - [The source API definition for TEMZ](https://github.com/yeongbba/temz-server/blob/dev/src/api/openapi.yaml)
  termsOfService: https://temz.io/terms
  contact:
    email: info@temz.com
  version: 1.0.0
externalDocs:
  description: Go to TEMZ website
  url: https://temz.io
servers:
  - url: 'http://localhost:8080'
tags:
  - name: auth
    description: Methods to handle authentication
  - name: verify
    description: Methods to verify mobile phone
paths:
  /auth/csrf:
    get: 
      tags: 
        - auth
      summary: Generates token to prevent csrf
      operationId: csrf
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: bad-request
            message: 'Your browser sent an invalid request'
            status: 400
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: not-found
            message: 'The specified resource was not found'
            status: 404
    InternerServer:
      description: Interner server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: interner-server
            message: 'Internal Server Error'
            status: 500
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        status: 
          type: integer
          format: int32
      required:
        - code
        - message
        - status
      example:
        code: invalid-value
        message: 'Invalid user or password'
        status: 401
  headers:
    CsrfToken:
      schema:
        type: string
      required: true
  securitySchemes:
    jwtAuth:
      description: Bearer token authorization with JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
    csrf:
      type: apiKey
      name: temz-csrf-token
      in: header
security:
  - jwtAuth: []
  - csrf: []