openapi: 3.0.3
info:
  title: TEMZ API
  description: |-
    This is a TEMZ Server based on the OpenAPI 3.0 specification.

    Some useful links:
    - [TEMZ server repository](https://github.com/yeongbba/temz-server)
    - [The source API definition for TEMZ](https://github.com/yeongbba/temz-server/blob/dev/src/api/openapi.yaml)
  termsOfService: https://temz.io/terms
  contact:
    email: info@temz.com
  version: 1.0.0
externalDocs:
  description: Go to TEMZ website
  url: https://temz.io
servers:
  - url: 'http://localhost:8080'
tags:
  - name: auth
    description: Methods to handle authentication
  - name: verify
    description: Methods to verify mobile phone
paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: Signs up a user to the TEMZ service
      description: Creates a user account for the given user details
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthApiResponse'
          headers: 
            Set-Cookie:
              schema:
                type: string
                example: JSESSIONID=abcde12345; Path=/; HttpOnly
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorApiResponse'
      security: []
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          minLength: 5
        name:
          type: string
        email:
          type: string
          format: email
        url:
          type: string
          format: url
      required:
        - username
        - password
        - email
        - name
      example:
        username: johndoe
        password: password
        name: John Doe
        email: john.doe@gmail.com
        url: 'https://awesomepics.com/878y766'
    AuthApiResponse:
      type: object
      properties:
        token:
          type: string
        username:
          type: string
      required:
        - token
        - username
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        username: johndoe
    ErrorApiResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
      example:
        message: "Something went wrong 🤪"
  securitySchemes:
    jwtAuth:
      description: Bearer token authorization with JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwtAuth: []