name: dev test before merge to main

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  IS_TEST: ${{ secrets.IS_TEST }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  ACCESS_EXPIRES_SEC: ${{ secrets.ACCESS_EXPIRES_SEC }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
  REFRESH_EXPIRES_SEC: ${{ secrets.REFRESH_EXPIRES_SEC }}
  ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
  REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
  BCRYPT_SALT_ROUNDS: ${{ secrets.BCRYPT_SALT_ROUNDS }}
  HOST_PORT: ${{ secrets.HOST_PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  RATE_LIMIT_DB: ${{ secrets.RATE_LIMIT_DB }}
  VERIFY_CODE_DB: ${{ secrets.VERIFY_CODE_DB }}
  CORS_ALLOW_ORIGIN: ${{ secrets.CORS_ALLOW_ORIGIN }}
  CSRF_SECRET_KEY: ${{ secrets.CSRF_SECRET_KEY }}
  CSRF_TOKEN_KEY: ${{ secrets.CSRF_TOKEN_KEY }}
  RATE_LIMIT_WINDOW_MS: ${{ secrets.RATE_LIMIT_WINDOW_MS }}
  RATE_LIMIT_MAX_REQUEST: ${{ secrets.RATE_LIMIT_MAX_REQUEST }}
  SENS_HOST_PHONE: ${{ secrets.SENS_HOST_PHONE }}
  SENS_SERVICE_ID: ${{ secrets.SENS_SERVICE_ID }}
  SENS_ACCESS_KEY: ${{ secrets.SENS_ACCESS_KEY }}
  SENS_SECRET_KEY: ${{ secrets.SENS_SECRET_KEY }}
  VERIFICATION_ALLOW_COUNT: ${{ secrets.VERIFICATION_ALLOW_COUNT }}
  VERIFICATION_GENERAL_EXPIRE_MINUTE: ${{ secrets.VERIFICATION_GENERAL_EXPIRE_MINUTE }}
  VERIFICATION_BLOCK_EXPIRE_MINUTE: ${{ secrets.VERIFICATION_BLOCK_EXPIRE_MINUTE }}
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_SERVICE_SID: ${{ secrets.TWILIO_SERVICE_SID }}
jobs:
  unit-test:
    environment: test
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: rebuild
        run: yarn rebuild
      - name: Test unit
        run: yarn test:unit:action
  auth-test:
    needs: unit-test
    environment: test
    env: 
      TEST_FILE: auth.test.ts
    name: auth integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 6.0
      - name: Setup Redis with password
        uses: getong/redis-action@v1
        with:
          redis password: ${{ secrets.REDIS_PW }}
      - name: rebuild
        run: yarn rebuild
      - name: Test integration
        run: yarn test:integration:action
      - name: If failure, test one more time
        if: failure()
        run: yarn test:integration:action
  bookmark-test:
    needs: unit-test
    environment: test
    env: 
      TEST_FILE: bookmark.test.ts
    name: integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 6.0
      - name: Setup Redis with password
        uses: getong/redis-action@v1
        with:
          redis password: ${{ secrets.REDIS_PW }}
      - name: rebuild
        run: yarn rebuild
      - name: Test integration
        run: yarn test:integration:action
      - name: If failure, test one more time
        if: failure()
        run: yarn test:integration:action