name: dev test before merge to main
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Test unit
        run: yarn test:unit
