name: Reusable integration test workflow

on:
  workflow_call:
    inputs:
      TEST_FILE:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    needs: unit-test
    environment: test
    env: 
      TEST_FILE: ${{ inputs.TEST_FILE }}
    name: ${{ inputs.TEST_FILE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: 6.0
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: rebuild
        run: yarn rebuild
      - name: Integration Test 
        run: yarn test:integration:action
      - name: If failure, test one more time
        if: failure()
        run: yarn test:integration:action